Time::DATE_FORMATS[:mdy_dots] = "%I:%M %p %B %d, %Y"
Time::DATE_FORMATS[:time_only] = "%I:%M %p"
Time::DATE_FORMATS[:date_only] = "%b %d"
Time::DATE_FORMATS[:year_only] = "%Y"

Time::DATE_FORMATS[:monetra] = "%m%y"
Time::DATE_FORMATS[:credit_card_exp] = "%m/%Y"
Time::DATE_FORMATS[:jquery] = "%m/%d/%Y"
Time::DATE_FORMATS[:standard_date] = "%m/%d/%Y"

Date::DATE_FORMATS[:monetra] = "%m%y"
Date::DATE_FORMATS[:credit_card_exp] = "%m/%Y"
Date::DATE_FORMATS[:jquery] = "%m/%d/%Y"
Date::DATE_FORMATS[:standard_date] = "%m/%d/%Y"
Date::DATE_FORMATS[:date_only] = "%b / %d"
Date::DATE_FORMATS[:year_only] = "%y"